### ISSUE TITLE
API Telemetry and APM for koa 

### ISSUE THREAD

**Issue by chong0808** [slanatech/swagger-stats#48] opened 2018-08-11 14:53 UTC
[for koa ](https://github.com/chong0808/swagger-stats-koa )
But encountered some problems
![tim 20180811225107](https://user-images.githubusercontent.com/16454649/43992966-1dd0c18c-9db9-11e8-9cdf-d35671b5b772.png)

**Comment by sv2** [comment] 2018-08-11 16:29
Wow, first of all - thank you for adopting it for Koa!

Looks like the issue is because in UI response to /stats request is received as text, not JSON 
In `SWSUI.prototype.refreshStats`

```
  var jqxhr = $.ajax(getdataReq)
            .done(function(msg) {
                // Login attempt successfull
                var xswsauth = jqxhr.getResponseHeader('x-sws-authenticated');
                if ((xswsauth !== undefined) && xswsauth && (xswsauth == 'true')) {
                    $('.sws-logout-ctrls').show();
                }

                // process received data as needed
                that.processStatsData(getdataDef, msg);
```
There `msg` is text, not object. As a result, further processing fails.

**Comment by sv2** [comment] 2018-08-11 16:41
Looks like when Koa returns response for /stats request, headers `Content-Length` and `Content-Type: application/json; charset=utf-8` are not set

**Comment by sv2** [comment] 2018-08-11 16:49
This is addressed by commenting out `ctx.res.writeHead(200)` in `swsInterfaceKoa.js`:

```
async function processGetStats(ctx) {
    //ctx.res.writeHead(200)
    var query = {};
    for (let key in ctx.request.query) {
        query['fields'] = ctx.request.query[key]
    };
    let content = swsProcessorkoa.getStats(query);
    // console.log(content)
    // content =
    ctx.body = content;
}
```
I think `writeHead` finalizes headers, and so Content-Type can't be added after it ... 

Good Luck !

**Closed** 2020-10-07 00:45 UTC
Labels: enhancement, question
